import Head from "next/head";
import { Inter } from "@next/font/google";
import {
  Box,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Heading,
  HStack,
  Image,
  Link,
  Text,
  VStack,
} from "@chakra-ui/react";
import { Quote } from "@/components/Quote";
import { CheckIcon, CloseIcon, EmailIcon, PhoneIcon } from "@chakra-ui/icons";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ruddy CPA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack background={"grey.400"} h="100vh" w="100%">
        <HStack pos={"sticky"} p="4" width={"100%"} justify="space-between">
          <Heading size={"md"}>Ruddy CPA</Heading>
          <HStack>
            <HStack>
              <PhoneIcon />
              <Link href="tel:7328143113">{"(732) 814-3113"}</Link>
            </HStack>
            <HStack>
              <EmailIcon />
              <Link href="mailto:mjruddy94@gmail.com?subject=Personal Tax Request">
                mjruddy94@gmail.com
              </Link>
            </HStack>
          </HStack>
        </HStack>
        <VStack>
          <Card w="650px">
            <CardHeader>
              <HStack justify={"space-between"}>
                <Heading size={"md"}>Matt Ruddy</Heading>
                <Text>Accounting Services</Text>
              </HStack>
            </CardHeader>
            <CardBody>
              <VStack>
                <Image
                  h="250px"
                  w="250px"
                  borderRadius={"lg"}
                  alt="ruddy cpa img"
                  src="/ruddy.jpg"
                />
                <Quote>
                  Matt Ruddy is a highly accomplished professional with a
                  diverse background in engineering and tax. He graduated from
                  Penn State with a Bachelor&apos;s degree in Engineering and
                  immediately began his career as an engineer, working on
                  complex projects for some of the top engineering firms in the
                  country. His experience in engineering gave him a strong
                  foundation in problem-solving, critical thinking, and
                  attention to detail, which has proven to be invaluable in his
                  later work as a tax specialist.
                  <br />
                  <br />
                  Despite his success as an engineer, Matt felt drawn to the
                  field of tax and decided to transition his career into this
                  new area of expertise. He went back to school to earn his
                  Master&apos;s degree in Taxation, which allowed him to gain a
                  deeper understanding of tax law and compliance. Matt&apos;s
                  ability to quickly grasp complex concepts and his attention to
                  detail made him a natural fit for the tax field, and he
                  quickly rose through the ranks to become a respected tax
                  specialist.
                  <br />
                  <br />
                  Throughout his career, Matt has worked with a wide variety of
                  clients, from individuals to small businesses to large
                  corporations, helping them navigate the complexities of tax
                  law and maximize their financial potential. He is known for
                  his ability to simplify complex tax concepts, his commitment
                  to providing excellent service, and his willingness to go
                  above and beyond for his clients.
                  <br />
                  <br />
                  Matt&apos;s passion for helping others extends beyond his work
                  as a tax specialist. He is actively involved in his community,
                  volunteering his time and resources to support local
                  organizations and causes. In his free time, Matt enjoys
                  hiking, skiing, and spending time with his family.
                </Quote>
              </VStack>
            </CardBody>
            <CardFooter>
              <Link href="mailto:mjruddy94@gmail.com?subject=Personal Tax Request">
                Contact
              </Link>
            </CardFooter>
          </Card>
        </VStack>
      </VStack>
    </>
  );
}

const CarouselText = ({ children }: { children: ReactNode }) => {
  return (
    <HStack w="auto" px="2" spacing="3">
      <Text
        _hover={{ color: "black" }}
        color="gray.400"
        whiteSpace={"nowrap"}
        fontWeight="bolder"
        fontSize="3xl"
        cursor={"default"}
      >
        {children}
      </Text>
    </HStack>
  );
};
